name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup black linter
        run: conda create --quiet --name black black

      - name: Lint python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check markovmeme

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup conda environment
        run: conda create --quiet --name markovmeme

      - name: Install mmeme
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate markovmeme
          python setup.py install

      - name: Test random generator
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          markov-meme generate
